[worker]
request_job_timeout = "40s"
allowed_domains = [ "localhost", "worker.osbuild.org" ]
enable_mtls = false
enable_jwt = true
jwt_keys_urls = ["http://fauxauth:8888/certs"]
jwt_acl_file = "/etc/osbuild-composer/acl.yml"
jwt_tenant_provider_fields = ["rh-org-id", "account_id"]
ca = "/etc/osbuild-composer/ca-crt.pem"
client_id = "rhsm-api"

[koji]
allowed_domains = [ "client.osbuild.org" ]
enable_mtls = false
enable_jwt = true
jwt_keys_urls = ["http://fauxauth:8888/certs"]
jwt_acl_file = "/etc/osbuild-composer/acl.yml"
jwt_tenant_provider_fields = ["rh-org-id", "account_id"]
ca = "/etc/osbuild-composer/ca-crt.pem"
client_id = "rhsm-api"
