[authentication]
oauth_url = "http://fauxauth:8888/token"
offline_token = "/etc/osbuild-worker/token"
client_id = "rhsm-api"
pg_host = "postgres"
pg_port = 5432
pg_database = "postgres"
pg_user = "postgres"
pg_password = "postgres"
